general:
  # The maximum number of characters that can be sent to the server
  max_characters: 100
  # Warning message will be shown when player tried to send a message that exceeds the limit
  warning_message_max: "§cわお！とっても香ばしいメッセージですね！%max_characters 文字までしか送れないんですよ！"
  # Warning message will be shown when player sent invaild command (e.g. /maxcharacters hogehoge)
  warning_message_invalid_command: "§cコマンドの使い方が間違っています。"
  # Success message will be shown when command player sent executed successfully.
  success_message: "§a設定を変更しました！"
  # Warning message will be shown when player does not have enough permission to execute the command.
  warning_message_no_permission: "§c権限がありません。"
  # Help message.
  help_message: "/regulatechat max <number> - チャットの最大文字数を設定します。\n/regulatechat reload - コンフィグファイルをリロードします。\n/regulatechat help - ヘルプを表示します。"
  # Message will be shown when the configuration file is reloaded.
  reload_message: "§aコンフィグファイルをリロードしました！"